# RaftBootstrapLinux.cmake
# Linux-specific build configuration for Raft projects
# Rob Dobson 2025

cmake_minimum_required(VERSION 3.16)

# Set C++ and C standards
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_C_STANDARD 11)

message(STATUS "\n------------------ CMAKE GENERATION PHASE (Linux)")

################################################
# SysTypes Header Generation
################################################

set(_systypes_out "${RAFT_BUILD_ARTIFACTS_FOLDER}/SysTypeInfoRecs.h")
set(_systypes_json "${BUILD_CONFIG_DIR}/SysTypes.json")
set(_systypes_template "${raftcore_SOURCE_DIR}/components/core/SysTypes/SysTypeInfoRecs.cpp.template")
set(_generate_script "${raftcore_SOURCE_DIR}/scripts/GenerateSysTypes.py")

message(STATUS "\n------------------ Generating SysTypeInfoRecs.h")
message(STATUS "Generating ${_systypes_out} from file ${_systypes_json}")

add_custom_command(
    OUTPUT ${_systypes_out}
    COMMAND python3 ${_generate_script} ${_systypes_json} ${_systypes_out} --cpp_template ${_systypes_template}
    DEPENDS ${_systypes_json} ${_systypes_template}
    WORKING_DIRECTORY ${RAFT_BUILD_ARTIFACTS_FOLDER}
    COMMENT "Generating SysTypeInfoRecs.h"
)

add_custom_target(
    GenerateSysTypeInfoRecs ALL
    DEPENDS ${_systypes_out}
    COMMENT "Auto-generating SysTypeInfoRecs.h"
)

################################################
# Linux SDK Config Header
################################################

# Create sdkconfig.h for Linux builds
set(_sdkconfig_out "${RAFT_BUILD_ARTIFACTS_FOLDER}/sdkconfig.h")

file(WRITE ${_sdkconfig_out} "// sdkconfig.h for Linux builds\n")
file(APPEND ${_sdkconfig_out} "// Auto-generated by RaftBootstrapLinux.cmake\n\n")
file(APPEND ${_sdkconfig_out} "#pragma once\n\n")
file(APPEND ${_sdkconfig_out} "// Disable ESP32-specific features for Linux\n")
file(APPEND ${_sdkconfig_out} "#undef CONFIG_BT_ENABLED\n")
file(APPEND ${_sdkconfig_out} "#undef CONFIG_ESP_WIFI_ENABLED\n")
file(APPEND ${_sdkconfig_out} "#undef CONFIG_ETH_USE_ESP32_EMAC\n")
file(APPEND ${_sdkconfig_out} "#undef CONFIG_ETH_USE_SPI_ETHERNET\n")
file(APPEND ${_sdkconfig_out} "#undef CONFIG_ETH_USE_OPENETH\n")
file(APPEND ${_sdkconfig_out} "#undef CONFIG_ETH_USE_RMII_ETHERNET\n")

# Create minimal esp_attr.h for Linux builds (should be removed from RaftMotorControl in future)
set(_esp_attr_out "${RAFT_BUILD_ARTIFACTS_FOLDER}/esp_attr.h")

file(WRITE ${_esp_attr_out} "// esp_attr.h stub for Linux builds\n")
file(APPEND ${_esp_attr_out} "// Auto-generated by RaftBootstrapLinux.cmake\n")
file(APPEND ${_esp_attr_out} "// This is a temporary shim - RaftMotorControl should use RaftArduino.h instead\n\n")
file(APPEND ${_esp_attr_out} "#pragma once\n\n")
file(APPEND ${_esp_attr_out} "// IRAM_ATTR is already defined in RaftArduino.h\n")
file(APPEND ${_esp_attr_out} "#ifndef IRAM_ATTR\n")
file(APPEND ${_esp_attr_out} "#define IRAM_ATTR\n")
file(APPEND ${_esp_attr_out} "#endif\n")

################################################
# DeviceTypeRecords Header Generation
################################################

set(_devtype_out "${RAFT_BUILD_ARTIFACTS_FOLDER}/DeviceTypeRecords_generated.h")
set(_devpoll_out "${RAFT_BUILD_ARTIFACTS_FOLDER}/DevicePollRecords_generated.h")
set(_devtype_json "${raftcore_SOURCE_DIR}/devtypes/DeviceTypeRecords.json")
set(_devtype_script "${raftcore_SOURCE_DIR}/scripts/ProcessDevTypeJsonToC.py")

message(STATUS "\n------------------ Generating DeviceTypeRecords_generated.h")

add_custom_command(
    OUTPUT ${_devtype_out} ${_devpoll_out}
    COMMAND python3 ${_devtype_script} ${_devtype_json} ${_devtype_out} ${_devpoll_out}
    DEPENDS ${_devtype_json}
    WORKING_DIRECTORY ${RAFT_BUILD_ARTIFACTS_FOLDER}
    COMMENT "Generating DeviceTypeRecords_generated.h and DevicePollRecords_generated.h"
)

add_custom_target(
    GenerateDeviceTypeRecords ALL
    DEPENDS ${_devtype_out} ${_devpoll_out}
    COMMENT "Auto-generating DeviceTypeRecords_generated.h and DevicePollRecords_generated.h"
)

################################################
# RaftCore Library
################################################

set(RAFTCORE_SOURCES
    ${raftcore_SOURCE_DIR}/components/core/Utils/RaftUtils.cpp
    ${raftcore_SOURCE_DIR}/components/core/Utils/RaftThreading.cpp
    ${raftcore_SOURCE_DIR}/components/core/ArduinoUtils/ArduinoWString.cpp
    ${raftcore_SOURCE_DIR}/components/core/ArduinoUtils/ArduinoTime.cpp
    ${raftcore_SOURCE_DIR}/components/core/ArduinoUtils/ArduinoGPIO.cpp
    ${raftcore_SOURCE_DIR}/components/core/DeviceManager/DeviceManager.cpp
    ${raftcore_SOURCE_DIR}/components/core/DeviceManager/DeviceFactory.cpp
    ${raftcore_SOURCE_DIR}/components/core/SysMod/RaftSysMod.cpp
    ${raftcore_SOURCE_DIR}/components/core/RaftDevice/RaftDevice.cpp
    ${raftcore_SOURCE_DIR}/components/core/SysManager/SysManager.cpp
    ${raftcore_SOURCE_DIR}/components/core/ConfigPinMap/ConfigPinMap.cpp
    ${raftcore_SOURCE_DIR}/components/core/SysTypes/SysTypeManager.cpp
    ${raftcore_SOURCE_DIR}/components/core/SupervisorStats/SupervisorStats.cpp
    ${raftcore_SOURCE_DIR}/components/core/RestAPIEndpoints/RestAPIEndpointManager.cpp
    ${raftcore_SOURCE_DIR}/components/core/Utils/PlatformUtils.cpp
    ${raftcore_SOURCE_DIR}/components/core/Bus/RaftBusSystem.cpp
    ${raftcore_SOURCE_DIR}/components/core/DeviceTypes/DeviceTypeRecords.cpp
    ${raftcore_SOURCE_DIR}/components/core/MiniHDLC/MiniHDLC.cpp
    ${raftcore_SOURCE_DIR}/components/core/FileSystem/FileSystem.cpp
    ${raftcore_SOURCE_DIR}/components/core/FileSystem/FileSystemChunker.cpp
    ${raftcore_SOURCE_DIR}/components/core/NamedValueProvider/NamedValueProvider.cpp
    ${raftcore_SOURCE_DIR}/components/core/RaftCoreApp/RaftCoreApp.cpp
    ${raftcore_SOURCE_DIR}/components/comms/RICRESTMsg/RICRESTMsg.cpp
    ${raftcore_SOURCE_DIR}/components/comms/ProtocolOverAscii/ProtocolOverAscii.cpp
    ${raftcore_SOURCE_DIR}/components/comms/CommsChannels/CommsChannelManager.cpp
    ${raftcore_SOURCE_DIR}/components/comms/CommsChannels/CommsChannel.cpp
    ${raftcore_SOURCE_DIR}/components/comms/ProtocolExchange/ProtocolExchange.cpp
    ${raftcore_SOURCE_DIR}/components/comms/ProtocolExchange/FileStreamSession.cpp
    ${raftcore_SOURCE_DIR}/components/comms/ProtocolBase/ProtocolBase.cpp
    ${raftcore_SOURCE_DIR}/components/comms/ProtocolRICSerial/ProtocolRICSerial.cpp
    ${raftcore_SOURCE_DIR}/components/comms/ProtocolRICFrame/ProtocolRICFrame.cpp
    ${raftcore_SOURCE_DIR}/components/comms/ProtocolRICJSON/ProtocolRICJSON.cpp
    ${raftcore_SOURCE_DIR}/components/comms/FileStreamProtocols/FileStreamBase.cpp
    ${raftcore_SOURCE_DIR}/components/comms/FileStreamProtocols/StreamDatagramProtocol.cpp
    ${raftcore_SOURCE_DIR}/components/comms/FileStreamProtocols/FileUploadHTTPProtocol.cpp
    ${raftcore_SOURCE_DIR}/components/comms/FileStreamProtocols/FileUploadOKTOProtocol.cpp
    ${raftcore_SOURCE_DIR}/components/comms/FileStreamProtocols/FileDownloadOKTOProtocol.cpp
    ${raftcore_SOURCE_DIR}/components/comms/CommsChannelMsg/CommsChannelMsg.cpp
)

set(RAFTCORE_INCLUDES
    ${raftcore_SOURCE_DIR}/components
    ${raftcore_SOURCE_DIR}/components/core/Utils
    ${raftcore_SOURCE_DIR}/components/core/ArduinoUtils
    ${raftcore_SOURCE_DIR}/components/core/RaftJson
    ${raftcore_SOURCE_DIR}/components/core/Logger
    ${raftcore_SOURCE_DIR}/components/core/APICommon
    ${raftcore_SOURCE_DIR}/components/core/RaftDevice
    ${raftcore_SOURCE_DIR}/components/core/DeviceManager
    ${raftcore_SOURCE_DIR}/components/core/SysMod
    ${raftcore_SOURCE_DIR}/components/core/SysManager
    ${raftcore_SOURCE_DIR}/components/core/RestAPIEndpoints
    ${raftcore_SOURCE_DIR}/components/core/ConfigPinMap
    ${raftcore_SOURCE_DIR}/components/core/Bus
    ${raftcore_SOURCE_DIR}/components/core/DeviceTypes
    ${raftcore_SOURCE_DIR}/components/core/DebounceButton
    ${raftcore_SOURCE_DIR}/components/core/ThreadSafeQueue
    ${raftcore_SOURCE_DIR}/components/core/SysTypes
    ${raftcore_SOURCE_DIR}/components/core/NamedValueProvider
    ${raftcore_SOURCE_DIR}/components/core/SupervisorStats
    ${raftcore_SOURCE_DIR}/components/core/DebugGlobals
    ${raftcore_SOURCE_DIR}/components/core/FileSystem
    ${raftcore_SOURCE_DIR}/components/core/MiniHDLC
    ${raftcore_SOURCE_DIR}/components/core/RaftCoreApp
    ${raftcore_SOURCE_DIR}/components/comms/CommsChannelMsg
    ${raftcore_SOURCE_DIR}/components/comms/CommsBridgeMsg
    ${raftcore_SOURCE_DIR}/components/comms/ProtocolExchange
    ${raftcore_SOURCE_DIR}/components/comms/ProtocolBase
    ${raftcore_SOURCE_DIR}/components/comms/CommsCoreIF
    ${raftcore_SOURCE_DIR}/components/comms/CommsChannels
    ${raftcore_SOURCE_DIR}/components/comms/ProtocolRawMsg
    ${raftcore_SOURCE_DIR}/components/comms/FileStreamProtocols
    ${raftcore_SOURCE_DIR}/components/comms/RICRESTMsg
    ${raftcore_SOURCE_DIR}/components/comms/ProtocolOverAscii
    ${raftcore_SOURCE_DIR}/components/comms/ProtocolRICSerial
    ${raftcore_SOURCE_DIR}/components/comms/ProtocolRICFrame
    ${raftcore_SOURCE_DIR}/components/comms/ProtocolRICJSON
    ${raftcore_SOURCE_DIR}/components/comms/ROSSerial
    ${RAFT_BUILD_ARTIFACTS_FOLDER}
)

add_library(RaftCoreLinux STATIC ${RAFTCORE_SOURCES})
target_include_directories(RaftCoreLinux PUBLIC ${RAFTCORE_INCLUDES})
add_dependencies(RaftCoreLinux GenerateSysTypeInfoRecs)

################################################
# RaftSysMods Library
################################################

set(RAFTSYSMODS_SOURCES
    ${raftsysmods_SOURCE_DIR}/components/SerialConsole/SerialConsole.cpp
    ${raftsysmods_SOURCE_DIR}/components/FileManager/FileManager.cpp
    ${raftsysmods_SOURCE_DIR}/components/StatePublisher/StatePublisher.cpp
    ${raftsysmods_SOURCE_DIR}/components/CommandFile/CommandFile.cpp
    ${raftsysmods_SOURCE_DIR}/components/CommandSerial/CommandSerial.cpp
)

set(RAFTSYSMODS_INCLUDES
    ${raftsysmods_SOURCE_DIR}/components/SerialConsole
    ${raftsysmods_SOURCE_DIR}/components/FileManager
    ${raftsysmods_SOURCE_DIR}/components/StatePublisher
    ${raftsysmods_SOURCE_DIR}/components/CommandFile
    ${raftsysmods_SOURCE_DIR}/components/CommandSerial
    ${raftsysmods_SOURCE_DIR}/components/RegisterSysMods
)

add_library(RaftSysModsLinux STATIC ${RAFTSYSMODS_SOURCES})
target_include_directories(RaftSysModsLinux PUBLIC ${RAFTSYSMODS_INCLUDES})
target_include_directories(RaftSysModsLinux PUBLIC ${RAFTCORE_INCLUDES})
target_link_libraries(RaftSysModsLinux PUBLIC RaftCoreLinux)

################################################
# RaftWebServer Library
################################################

set(RAFTWEBSERVER_SOURCES
    ${raftwebserver_SOURCE_DIR}/components/RaftWebServer/RaftWebServer.cpp
    ${raftwebserver_SOURCE_DIR}/components/RaftWebServer/RaftWebConnManager.cpp
    ${raftwebserver_SOURCE_DIR}/components/RaftWebServer/RaftClientListener.cpp
    ${raftwebserver_SOURCE_DIR}/components/RaftWebServer/RaftClientConnSockets.cpp
    ${raftwebserver_SOURCE_DIR}/components/RaftWebServer/RaftWebSocketLink.cpp
    ${raftwebserver_SOURCE_DIR}/components/RaftWebServer/RaftWebHandlerRestAPI.cpp
    ${raftwebserver_SOURCE_DIR}/components/RaftWebServer/RaftWebHandlerStaticFiles.cpp
    ${raftwebserver_SOURCE_DIR}/components/RaftWebServer/RaftWebHandlerWS.cpp
    ${raftwebserver_SOURCE_DIR}/components/RaftWebServer/RaftWebResponderFile.cpp
    ${raftwebserver_SOURCE_DIR}/components/RaftWebServer/RaftWebResponderRestAPI.cpp
    ${raftwebserver_SOURCE_DIR}/components/RaftWebServer/RaftWebResponderWS.cpp
    ${raftwebserver_SOURCE_DIR}/components/RaftWebServer/RaftWebConnection.cpp
    ${raftwebserver_SOURCE_DIR}/components/RaftWebServer/RaftWebInterface.cpp
    ${raftwebserver_SOURCE_DIR}/components/RaftWebServer/RaftWebMultipart.cpp
    ${raftwebserver_SOURCE_DIR}/components/WebServer/WebServer.cpp
)

set(RAFTWEBSERVER_INCLUDES
    ${raftwebserver_SOURCE_DIR}/components/RaftWebServer
    ${raftwebserver_SOURCE_DIR}/components/WebServer
    ${raftwebserver_SOURCE_DIR}/components
)

add_library(RaftWebServerLinux STATIC ${RAFTWEBSERVER_SOURCES})
target_include_directories(RaftWebServerLinux PUBLIC ${RAFTWEBSERVER_INCLUDES})
target_include_directories(RaftWebServerLinux PUBLIC ${RAFTCORE_INCLUDES})
target_link_libraries(RaftWebServerLinux PUBLIC RaftCoreLinux)
target_compile_definitions(RaftWebServerLinux PUBLIC
    __linux__
)

################################################
# RaftMotorControl Library
################################################

set(RAFTMOTORCONTROL_SOURCES
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/MotorControl.cpp
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/Controller/MotionArgs.cpp
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/Controller/MotionBlockManager.cpp
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/Controller/MotionController.cpp
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/Controller/MotionPlanner.cpp
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/RampGenerator/MotionBlock.cpp
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/RampGenerator/MotionPipeline.cpp
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/RampGenerator/RampGenStats.cpp
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/RampGenerator/RampGenTimer.cpp
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/RampGenerator/RampGenerator.cpp
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/Axes/AxisEndstopChecks.cpp
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/EndStops/EndStops.cpp
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/Steppers/StepDriverBase.cpp
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/Steppers/StepDriverTMC2209.cpp
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/MotionPatterns/HomingPattern.cpp
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/MotionPatterns/MotionPatternManager.cpp
)

set(RAFTMOTORCONTROL_INCLUDES
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/.
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/Axes
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/Controller
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/Kinematics
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/RampGenerator
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/Steppers
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/EndStops
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/MotorEnabler
    ${raftmotorcontrol_SOURCE_DIR}/components/MotorControl/MotionPatterns
)

add_library(RaftMotorControlLinux STATIC ${RAFTMOTORCONTROL_SOURCES})
target_include_directories(RaftMotorControlLinux PUBLIC ${RAFTMOTORCONTROL_INCLUDES})
target_include_directories(RaftMotorControlLinux PUBLIC ${RAFTCORE_INCLUDES})
target_link_libraries(RaftMotorControlLinux PUBLIC RaftCoreLinux)

################################################
# Project Setup
################################################

# Define the project
project(${PROJECT_BASENAME} C CXX)

# Override project() macro to prevent main CMakeLists.txt from calling it again
# This must be done AFTER our project() call but BEFORE returning to main CMakeLists.txt
macro(project)
    # Do nothing - project already defined for Linux build
endmacro()

message(STATUS "\n------------------ Firmware image ${PROJECT_BASENAME} ------------------")
message(STATUS "Build artifacts folder: ${RAFT_BUILD_ARTIFACTS_FOLDER}")
message(STATUS "RaftCore source: ${raftcore_SOURCE_DIR}")
message(STATUS "RaftSysMods source: ${raftsysmods_SOURCE_DIR}")
message(STATUS "RaftWebServer source: ${raftwebserver_SOURCE_DIR}")
message(STATUS "RaftMotorControl source: ${raftmotorcontrol_SOURCE_DIR}")

################################################
# WebUI Build and Deployment
################################################

# Check if UI_SOURCE_PATH is defined in features.cmake
if(DEFINED UI_SOURCE_PATH)
    # Convert relative path to absolute
    if(NOT IS_ABSOLUTE ${UI_SOURCE_PATH})
        set(_ui_source_path "${BUILD_CONFIG_DIR}/${UI_SOURCE_PATH}")
    else()
        set(_ui_source_path "${UI_SOURCE_PATH}")
    endif()
    
    # WebUI output directory
    set(_ui_output_dir "${CMAKE_BINARY_DIR}/linuxfs")
    
    message(STATUS "WebUI source: ${_ui_source_path}")
    message(STATUS "WebUI output: ${_ui_output_dir}")
    
    # Check if package.json exists (indicating a buildable WebUI)
    if(EXISTS "${_ui_source_path}/package.json")
        # Add custom target to build WebUI
        add_custom_target(BuildWebUI
            COMMAND ${CMAKE_COMMAND} -E echo "Building WebUI..."
            COMMAND bash -c "cd ${_ui_source_path} && if [ ! -d node_modules ]; then npm install; fi && npm run build"
            COMMAND ${CMAKE_COMMAND} -E echo "Copying WebUI to ${_ui_output_dir}..."
            COMMAND ${CMAKE_COMMAND} -E make_directory ${_ui_output_dir}
            COMMAND ${CMAKE_COMMAND} -E copy_directory ${_ui_source_path}/dist ${_ui_output_dir}
            COMMENT "Building and deploying WebUI"
            VERBATIM
        )
        message(STATUS "WebUI build target created - run 'make BuildWebUI' to build")
    else()
        message(STATUS "No package.json found in ${_ui_source_path}, skipping WebUI build")
    endif()
else()
    message(STATUS "UI_SOURCE_PATH not defined, skipping WebUI setup")
endif()

################################################
# Application Sources
################################################

# Find all source files in main and components folders
file(GLOB_RECURSE APP_SOURCES 
    ${CMAKE_SOURCE_DIR}/main/*.cpp
    ${CMAKE_SOURCE_DIR}/components/*/*.cpp
)

# Application includes
set(APP_INCLUDES
    ${CMAKE_SOURCE_DIR}/main
    ${CMAKE_SOURCE_DIR}/components/SandBot/SandBot
)

################################################
# Executable Target
################################################

add_executable(${PROJECT_BASENAME} ${APP_SOURCES})

target_include_directories(${PROJECT_BASENAME} PRIVATE
    ${APP_INCLUDES}
    ${RAFTCORE_INCLUDES}
    ${RAFTSYSMODS_INCLUDES}
    ${RAFTWEBSERVER_INCLUDES}
    ${RAFTMOTORCONTROL_INCLUDES}
)

target_link_libraries(${PROJECT_BASENAME} PRIVATE
    RaftCoreLinux
    RaftSysModsLinux
    RaftWebServerLinux
    RaftMotorControlLinux
    pthread
    mbedtls
    mbedcrypto
    mbedx509
)

target_compile_definitions(${PROJECT_BASENAME} PRIVATE
    __linux__
    WEB_CONN_USE_BERKELEY_SOCKETS
)

message(STATUS "Executable target: ${PROJECT_BASENAME}")
message(STATUS "Application sources: ${CMAKE_SOURCE_DIR}/main and ${CMAKE_SOURCE_DIR}/components")
